import Foundation

extension TVStrings {
    static let italian = TVStrings(
        tagline: "Pulisci il Mac. I tasti possono aspettare.",
        tabCleaning: "Pulizia", tabBreak: "Pausa",
        durationLabel: "Durata della pulizia", themeLabel: "Tema dello schermo",
        startCleaning: "Inizia la pulizia", cleaningInProgress: "Pulizia in corso…",
        previewButton: "Anteprima (senza bloccare)",
        unlockHintMenu: "Tieni premuto **esc** per %@ s per sbloccare.",
        settings: "Impostazioni…", quit: "Esci",
        language: "Lingua", systemLanguage: "Lingua di sistema (%@)",

        secondsChoice: "%d secondi", minutesChoice: "%d minuti", unlimited: "Senza limite",

        themeDarkShort: "Scuro", themeLightShort: "Chiaro", themeColorShort: "Colore",
        themeDarkLong: "Scuro (mostra meglio la polvere)",
        themeLightLong: "Chiaro (mostra meglio le impronte)",
        themeColorLong: "Colorato",

        permissionTitle: "Serve il permesso di accessibilità",
        permissionBody: "Per bloccare tastiera e trackpad, autorizza Temizlik Vakti in Impostazioni di Sistema → Privacy e sicurezza → Accessibilità.",
        permissionRequest: "Richiedi accesso", permissionOpenSettings: "Apri Impostazioni",
        permissionRelaunch: "Riavvia app",
        permissionStaleNote: "Se l'hai già concesso e l'avviso resta, riavvia l'app: a volte macOS aggiorna un permesso scaduto solo così.",
        permissionGranted: "Accesso all'accessibilità concesso",
        permissionMissing: "Nessun accesso all'accessibilità",

        unlockHold: "Tieni premuto per sbloccare", unlockHolding: "Non mollare…",
        lockFooterNote: "Tastiera e trackpad bloccati · Se l'app si chiude, l'input torna subito",
        unlimitedSession: "Sessione senza limite",
        allClean: "Splendente!",
        perfectRun: "Giro perfetto: non hai toccato un tasto",
        sessionSummary: "Tempo di pulizia: %@ · input bloccati: %d",

        eggParty: "Codice segreto accettato. Modalità festa!",
        eggAnnoyed: "Va bene, va bene! Ho capito!",
        eggDizzy: "Ok, mi gira la testa…",
        eggSleepy: "Zzz… pulisci tu, io schiaccio un pisolino.",
        eggCaps: "Non serve urlare, sono qui.",
        eggSecret: "La parola magica! La spugna ti adora.",

        breakTitle: "Pausa per gli occhi", breakOver: "Pausa finita",
        breakSnooze: "Rimanda 5 min", breakSkip: "Salta la pausa",
        breakEscHint: "anche esc salta la pausa",
        breakStrictHint: "Modalità rigida · tastiera e trackpad bloccati",
        breakStrictUnlock: "Tieni premuto per saltare la pausa",
        breakToggle: "Promemoria pausa occhi", breakWork: "Lavoro", breakLength: "Pausa",
        breakStrictMode: "Modalità rigida — blocca l'input durante la pausa",
        breakSkipWhenIdle: "Salta la pausa se non sono al computer",
        breakNow: "Pausa ora", breakPauseHour: "Sospendi 1 h", breakResume: "Riprendi",
        breakRuleNote: "20-20-20: ogni 20 minuti guarda a ~6 metri per 20 secondi.",
        breakDisabled: "Promemoria disattivato",
        breakPaused: "In pausa — mancano %@", breakNext: "Prossima pausa: %@",
        breakScheduling: "Pianificazione…",

        settingsSession: "Sessione", settingsAppearance: "Aspetto", settingsGeneral: "Generali",
        settingsDuration: "Durata", settingsPreroll: "Conto alla rovescia iniziale: %d s",
        settingsUnlockHold: "Tenere esc per sbloccare: %@ s",
        settingsTheme: "Tema", settingsShowMascot: "Mostra la mascotte",
        settingsSnark: "Commenti pungenti", settingsBubbles: "Bolle di sapone",
        settingsHideCursor: "Nascondi il puntatore", settingsSounds: "Effetti sonori",
        settingsLaunchAtLogin: "Avvia al login", settingsRefresh: "Aggiorna",
        settingsOpenSettings: "Apri Impostazioni",
        settingsEasterEggNote: "Anche con l'input bloccato, la mascotte segue con gli occhi i tuoi movimenti sul trackpad. Ci sono chicche nascoste: inserisci il codice classico, scrivi \"temiz\", oppure non toccare niente per un po'.",
        settingsShortcutNote: "Scorciatoia: Controllo + Opzione + Comando + C avvia la pulizia. Tasto di accensione, Touch ID e alcuni tasti hardware sono protetti da macOS e non si possono bloccare. Se l'app si chiude, l'input torna subito.",
        settingsBreakSection: "Pausa per gli occhi (20-20-20)",
        settingsBreakNote: "Ogni %d minuti compare una schermata di pausa di %d secondi. Con la modalità rigida disattivata puoi saltarla con esc o rimandarla di 5 minuti.",

        snark: [
            "Non saltare l'angolo in basso a destra. Lo vedo.",
            "Quella briciola sotto la tastiera è del 2019, comunque.",
            "Pulisci lo schermo, non l'impostazione della luminosità.",
            "Sul trackpad hai allestito una vera galleria di impronte.",
            "Usa un panno in microfibra. La maglietta non lo è.",
            "Mai spruzzare direttamente sullo schermo. Sul panno. Per favore.",
            "Sotto la barra spaziatrice vive un intero ecosistema.",
            "Non detergente per vetri: acqua distillata e microfibra.",
            "Non dimenticare le griglie di ventilazione, il museo della polvere.",
            "Perfino il tuo chip M3 si vergogna di questo sporco.",
            "Ora il logo Apple sul coperchio. Deve brillare.",
            "Panno umido, non bagnato. La differenza è la garanzia."
        ],
        preroll: ["Mani in alto, sto bloccando…", "Panno pronto?", "Tre… due… uno… si pulisce!"],
        blocked: ["Bel tentativo, è bloccato.", "Quel tasto è in vacanza.",
                  "Smetti di premere, continua a pulire.", "Toc toc. Non c'è nessuno.",
                  "Ci hai provato. Niente. Torna al panno."],
        finished: ["Splendente. Puoi fissarlo per cinque minuti.", "Ecco! Come nuovo.",
                   "Brilla. Tieni lontano il caffè.", "Fatto. Alla salute."],
        breakTips: [
            "Guarda a ~6 metri per 20 secondi. I tuoi occhi ringrazieranno.",
            "Sbatti le palpebre di proposito: davanti allo schermo lo fai metà del normale.",
            "Alza le spalle verso le orecchie, conta fino a tre, rilascia.",
            "Guarda fuori dalla finestra. Scegli un punto lontano.",
            "Alzati, fai due passi. La tua schiena se lo ricorda.",
            "Respiro profondo: 4 secondi dentro, 6 fuori.",
            "Ruota i polsi in entrambe le direzioni, apri e chiudi le dita.",
            "La luminosità dello schermo è in linea con la stanza? Controlla.",
            "Bevi acqua. Sì, adesso.",
            "Gira il collo lentamente a destra e a sinistra. Senza forzare."
        ],
        breakDone: ["Pausa finita, riprendi da dove eri.", "Occhi riposati. Andiamo.", "Ricaricato. Avanti!"]
    )
}
