import Foundation

extension TVStrings {
    static let turkish = TVStrings(
        tagline: "Mac'ini sil, tuşlara basma derdi yok.",
        tabCleaning: "Temizlik",
        tabBreak: "Mola",
        durationLabel: "Temizlik süresi",
        themeLabel: "Ekran teması",
        startCleaning: "Temizliğe Başla",
        cleaningInProgress: "Temizlik sürüyor…",
        previewButton: "Önizle (kilitlemeden)",
        unlockHintMenu: "Kilidi açmak için **esc** tuşunu %@ sn basılı tut.",
        settings: "Ayarlar…",
        quit: "Çıkış",
        language: "Dil",
        systemLanguage: "Sistem dili (%@)",
        secondsChoice: "%d saniye",
        secondsChoiceOne: "1 saniye",
        minutesChoice: "%d dakika",
        minutesChoiceOne: "1 dakika",
        unlimited: "Süresiz",
        countdownHoursMinutes: "%d sa %02d dk",

        themeDarkShort: "Koyu",
        themeLightShort: "Açık",
        themeColorShort: "Renkli",
        themeDarkLong: "Koyu (ekran tozu için)",
        themeLightLong: "Açık (kir/leke için)",
        themeColorLong: "Renkli",

        permissionTitle: "Erişilebilirlik izni gerekli",
        permissionBody: "Klavye ve trackpad'i kilitleyebilmek için Sistem Ayarları → Gizlilik ve Güvenlik → Erişilebilirlik listesinde Temizlik Vakti'ne izin ver.",
        permissionRequest: "İzin İste",
        permissionOpenSettings: "Ayarları Aç",
        permissionRelaunch: "Yeniden Başlat",
        permissionStaleNote: "İzni verdiğin hâlde bu uyarı kalıyorsa uygulamayı yeniden başlat; macOS eski izin kaydını bazen ancak o zaman tazeler.",
        permissionGranted: "Erişilebilirlik izni verildi",
        permissionMissing: "Erişilebilirlik izni yok",

        unlockHold: "Kilidi açmak için basılı tut",
        unlockHolding: "Bırakma…",
        lockFooterNote: "Klavye ve trackpad kilitli · Uygulama kapanırsa kilit otomatik açılır",
        previewFooterNote: "ÖNİZLEME · Giriş kilitli DEĞİL · Çıkmak için herhangi bir tuşa bas veya tıkla",
        unlimitedSession: "Süresiz oturum",
        allClean: "Tertemiz!",
        perfectRun: "Kusursuz tur — hiç tuşa dokunmadın",
        sessionSummary: "Temizlik süresi: %@ · engellenen girdi: %d",

        eggParty: "Hile kodu kabul edildi. Parti modu!",
        eggAnnoyed: "Tamam tamam! Anladım!",
        eggDizzy: "Tamam, başım döndü…",
        eggSleepy: "Zzz… sen sil, ben kestireyim.",
        eggCaps: "Bağırmana gerek yok, buradayım.",
        eggSecret: "Doğru kelime! Sünger seni sevdi.",

        breakTitle: "Göz Molası",
        breakOver: "Mola bitti",
        breakSnooze: "5 dk ertele",
        breakSkip: "Molayı geç",
        breakEscHint: "esc tuşu da molayı geçer",
        breakStrictHint: "Katı mod açık · klavye ve trackpad kilitli",
        breakStrictUnlock: "Molayı geçmek için basılı tut",
        breakToggle: "Göz molası hatırlatıcısı",
        breakWork: "Çalışma",
        breakLength: "Mola",
        breakStrictMode: "Katı mod — molada girişi kilitle",
        breakSkipWhenIdle: "Bilgisayar başında değilsem molayı atla",
        breakNow: "Şimdi mola",
        breakPauseHour: "1 sa duraklat",
        breakResume: "Devam",
        breakRuleNote: "20-20-20: her 20 dakikada bir, 20 saniye boyunca ~6 metre uzağa bak.",
        breakDisabled: "Hatırlatıcı kapalı",
        breakPaused: "Duraklatıldı — %@ kaldı",
        breakNext: "Sonraki mola: %@",
        breakScheduling: "Planlanıyor…",

        settingsSession: "Oturum",
        settingsAppearance: "Görünüm",
        settingsGeneral: "Genel",
        settingsDuration: "Süre",
        settingsPreroll: "Başlangıç geri sayımı: %d sn",
        settingsUnlockHold: "Kilidi açmak için esc basılı tutma: %@ sn",
        settingsTheme: "Tema",
        settingsShowMascot: "Maskotu göster",
        settingsSnark: "Laf sokan yorumlar",
        settingsBubbles: "Sabun köpükleri",
        settingsHideCursor: "İmleci gizle",
        settingsSounds: "Ses efektleri",
        settingsLaunchAtLogin: "Girişte başlat",
        settingsRefresh: "Yenile",
        settingsOpenSettings: "Ayarları Aç",
        settingsEasterEggNote: "Maskot, kilitliyken bile trackpad hareketlerini izleyip gözleriyle seni takip eder. Gizli numaralar var: klasik hile kodunu gir, \"temiz\" yaz, ya da bir süre hiçbir şeye dokunma ve ne olduğunu gör.",
        settingsShortcutNote: "Kısayol: Kontrol + Seçenek + Komut + C ile temizliği başlatabilirsin. Güç düğmesi, Touch ID ve bazı donanım tuşları macOS tarafından korunur; bunlar kilitlenemez. Uygulama kapanırsa kilit anında açılır.",
        settingsBreakSection: "Göz molası (20-20-20)",
        settingsBreakNote: "Her %d dakikada bir %d saniyelik mola ekranı açılır. Katı mod kapalıyken molayı esc ile geçebilir ya da 5 dakika erteleyebilirsin.",

        snark: [
            "Şu sağ alt köşeyi es geçme, seni görüyorum.",
            "Klavyenin arasındaki kırıntı 2019'dan kalma bu arada.",
            "Ekran parlaklığını değil, ekranı sil.",
            "Trackpad'de bir parmak izi galerisi açmışsın.",
            "Mikrofiber bez kullan. Tişörtün bez değil.",
            "Doğrudan ekrana sıvı sıkma. Beze sık. Lütfen.",
            "Space tuşunun altında bir ekosistem var.",
            "Enter'a bugün 4.312 kez bastın, hakkını ver.",
            "Şu yağ lekesi… kahvaltıda ne yedin?",
            "Fan deliklerini de unutma, orası toz müzesi.",
            "Kapak menteşesinin arası. Evet, orası.",
            "M3 çipin bile bu kirden utandı.",
            "Bu arada güzel gidiyorsun. Şaka yaptım, sol tarafa bak.",
            "Cam temizleyici değil, damıtılmış su + mikrofiber.",
            "Ekranda gördüğün nokta toz değil, kırık piksel olabilir. Şaka. Belki.",
            "Kablo girişlerini de sil ama sıvıdan uzak dur.",
            "Klavyeyi ters çevirip hafifçe salla. Hafifçe dedim.",
            "Alt kapak da senin Mac'inin bir parçası.",
            "Şimdi de arkadaki elma logosu. O parlamalı.",
            "Tuşların arasına basınçlı hava, ama çok yakından değil.",
            "Bilerek söylüyorum: caps lock'un kenarı hâlâ kirli.",
            "Şu an klavyeye bassan da olmuyor. Rahatla.",
            "Temizlik bitince kahve dökmemeye çalış, anlaştık mı?",
            "Ekranı dairesel değil, yumuşak yatay hareketlerle sil.",
            "Trackpad'i silerken kenarlarını da dahil et.",
            "Toz alerjin varsa maske takabilirdin.",
            "Sen sildikçe ben tozu sayıyorum. 4.891… 4.892…",
            "Vidalarla oynama, garanti diye bir şey var.",
            "Şarj kablosunun ucu da bir hayli yıpranmış.",
            "Bir sonraki temizlik için takvime not düşelim mi?",
            "Islak bez değil, nemli bez. Aradaki fark: garanti.",
            "Ekrandaki o çizik benim suçum değil.",
            "Bu kadar kir birikmesi için epey emek vermişsin.",
            "Klavye aydınlatmasını kapattım, kir daha net görünüyor.",
            "Hoparlör ızgaraları: kaşifler için son sınır.",
            "Kamera lensini de sil, toplantıda pusluyorsun.",
            "Bu mola sana da iyi geldi, kabul et.",
            "Az kaldı. Ya da değil. Süreyi sen ayarladın.",
            "Alkolü %70'i geçmesin, kaplamaya zarar verir.",
            "Bir de şu köşe. Hep aynı köşe."
        ],
        preroll: [
            "Elini kaldır, kilitliyorum…",
            "Bez hazır mı?",
            "Üç… iki… bir… temizlik vakti!",
            "Yerlerinize, hazır…"
        ],
        blocked: [
            "Boşuna uğraşma, kilitli.",
            "O tuş şu an tatilde.",
            "Basmayı bırak, silmeye devam et.",
            "Tık tık. Cevap yok.",
            "Denedin, olmadı. Beze dön.",
            "Tuşlar seni duymuyor."
        ],
        finished: [
            "Tertemiz. Şimdi 5 dakika buna bakabilirsin.",
            "İşte bu! Yeni gibi oldu.",
            "Pırıl pırıl. Kahveyi uzak tut.",
            "Bitti. Şerefine.",
            "Mac'in teşekkür etti, duymadın mı?"
        ],
        breakTips: [
            "20 saniye boyunca ~6 metre uzağa bak. Gözlerin teşekkür edecek.",
            "Birkaç kez bilinçli göz kırp — ekrana bakarken göz kırpma hızın yarıya iniyor.",
            "Omuzlarını kulaklarına çek, üçe say, bırak.",
            "Pencereden dışarı bak. Uzak bir nokta seç ve odaklan.",
            "Ayağa kalk, birkaç adım at. Sırtın hatırlar.",
            "Derin bir nefes: 4 saniye al, 6 saniye ver.",
            "Bileklerini iki yöne de çevir, parmaklarını aç kapa.",
            "Ekranın parlaklığı odanın aydınlığıyla uyumlu mu? Kontrol et.",
            "Su iç. Evet, şimdi.",
            "Boynunu yavaşça sağa sola çevir, zorlama.",
            "Gözlerini 10 saniye kapat, sadece dinlensinler.",
            "Oturuşunu düzelt: ayaklar yerde, ekran göz hizasında."
        ],
        breakDone: [
            "Mola bitti, kaldığın yerden devam.",
            "Gözlerin dinlendi. Hadi bakalım.",
            "Tamamdır, çalışmaya dön.",
            "Şarj oldun. Devam!"
        ]
    )
}
