import Foundation

extension TVStrings {
    static let spanish = TVStrings(
        tagline: "Limpia tu Mac. Las teclas pueden esperar.",
        tabCleaning: "Limpieza", tabBreak: "Descanso",
        durationLabel: "Duración de la limpieza", themeLabel: "Tema de pantalla",
        startCleaning: "Empezar limpieza", cleaningInProgress: "Limpieza en curso…",
        previewButton: "Vista previa (sin bloquear)",
        unlockHintMenu: "Mantén **esc** %@ s para desbloquear.",
        settings: "Ajustes…", quit: "Salir",
        language: "Idioma", systemLanguage: "Idioma del sistema (%@)",
        secondsChoice: "%d segundos",
        secondsChoiceOne: "1 segundo",
        minutesChoice: "%d minutos",
        minutesChoiceOne: "1 minuto",
        unlimited: "Sin límite",
        countdownHoursMinutes: "%d h %02d min",

        themeDarkShort: "Oscuro", themeLightShort: "Claro", themeColorShort: "Color",
        themeDarkLong: "Oscuro (muestra mejor el polvo)",
        themeLightLong: "Claro (muestra mejor las huellas)",
        themeColorLong: "Colorido",

        permissionTitle: "Se necesita permiso de accesibilidad",
        permissionBody: "Para bloquear el teclado y el trackpad, autoriza Temizlik Vakti en Ajustes del Sistema → Privacidad y seguridad → Accesibilidad.",
        permissionRequest: "Solicitar acceso", permissionOpenSettings: "Abrir Ajustes",
        permissionRelaunch: "Reiniciar app",
        permissionStaleNote: "Si ya lo concediste y el aviso sigue, reinicia la app: a veces macOS solo entonces actualiza un registro de permiso caducado.",
        permissionGranted: "Acceso de accesibilidad concedido",
        permissionMissing: "Sin acceso de accesibilidad",

        unlockHold: "Mantén para desbloquear", unlockHolding: "No sueltes…",
        lockFooterNote: "Teclado y trackpad bloqueados · Si la app se cierra, la entrada vuelve al instante",
        unlimitedSession: "Sesión sin límite",
        allClean: "¡Impecable!",
        perfectRun: "Ronda perfecta: no tocaste ni una tecla",
        sessionSummary: "Tiempo de limpieza: %@ · entradas bloqueadas: %d",

        eggParty: "Código secreto aceptado. ¡Modo fiesta!",
        eggAnnoyed: "¡Vale, vale! ¡Ya lo pillo!",
        eggDizzy: "Vale, me estoy mareando…",
        eggSleepy: "Zzz… tú limpia, yo echo una siesta.",
        eggCaps: "No hace falta gritar, estoy aquí.",
        eggSecret: "¡La palabra mágica! A la esponja le caes bien.",

        breakTitle: "Descanso visual", breakOver: "Descanso terminado",
        breakSnooze: "Posponer 5 min", breakSkip: "Saltar descanso",
        breakEscHint: "esc también salta el descanso",
        breakStrictHint: "Modo estricto · teclado y trackpad bloqueados",
        breakStrictUnlock: "Mantén para saltar el descanso",
        breakToggle: "Recordatorio de descanso visual", breakWork: "Trabajo", breakLength: "Descanso",
        breakStrictMode: "Modo estricto: bloquear la entrada durante el descanso",
        breakSkipWhenIdle: "Saltar el descanso si no estoy delante",
        breakNow: "Descansar ahora", breakPauseHour: "Pausar 1 h", breakResume: "Reanudar",
        breakRuleNote: "20-20-20: cada 20 minutos, mira a ~6 metros durante 20 segundos.",
        breakDisabled: "Recordatorio desactivado",
        breakPaused: "En pausa: quedan %@", breakNext: "Próximo descanso: %@",
        breakScheduling: "Programando…",

        settingsSession: "Sesión", settingsAppearance: "Apariencia", settingsGeneral: "General",
        settingsDuration: "Duración", settingsPreroll: "Cuenta atrás inicial: %d s",
        settingsUnlockHold: "Mantener esc para desbloquear: %@ s",
        settingsTheme: "Tema", settingsShowMascot: "Mostrar mascota",
        settingsSnark: "Comentarios socarrones", settingsBubbles: "Burbujas de jabón",
        settingsHideCursor: "Ocultar el cursor", settingsSounds: "Efectos de sonido",
        settingsLaunchAtLogin: "Abrir al iniciar sesión", settingsRefresh: "Actualizar",
        settingsOpenSettings: "Abrir Ajustes",
        settingsEasterEggNote: "Incluso con la entrada bloqueada, la mascota sigue tus movimientos del trackpad con la mirada. Hay trucos ocultos: introduce el código clásico, escribe \"temiz\", o no toques nada durante un rato.",
        settingsShortcutNote: "Atajo: Control + Opción + Comando + C inicia la limpieza. El botón de encendido, Touch ID y algunas teclas de hardware están protegidos por macOS y no se pueden bloquear. Si la app se cierra, la entrada vuelve al instante.",
        settingsBreakSection: "Descanso visual (20-20-20)",
        settingsBreakNote: "Cada %d minutos aparece una pantalla de descanso de %d segundos. Con el modo estricto desactivado puedes saltarla con esc o posponerla 5 minutos.",

        snark: [
            "No te saltes la esquina inferior derecha. La estoy viendo.",
            "Por cierto, esa miga bajo el teclado es de 2019.",
            "Limpia la pantalla, no el ajuste de brillo.",
            "Has montado toda una galería de huellas en el trackpad.",
            "Usa un paño de microfibra. Tu camiseta no lo es.",
            "Nunca rocíes directamente la pantalla. Al paño. Por favor.",
            "Bajo la barra espaciadora hay todo un ecosistema.",
            "Limpiacristales no: agua destilada y microfibra.",
            "No olvides las rejillas de ventilación, el museo del polvo.",
            "Hasta tu chip M3 se avergüenza de esta suciedad.",
            "Ahora el logo de Apple de la tapa. Tiene que brillar.",
            "Paño húmedo, no mojado. La diferencia es tu garantía."
        ],
        preroll: ["Aparta las manos, bloqueo…", "¿Paño listo?", "Tres… dos… uno… ¡a limpiar!"],
        blocked: ["Buen intento, está bloqueado.", "Esa tecla está de vacaciones.",
                  "Deja de pulsar, sigue limpiando.", "Toc toc. No hay nadie.",
                  "Lo intentaste. No funcionó. Vuelve al paño."],
        finished: ["Impecable. Puedes quedarte mirándolo cinco minutos.", "¡Ahí está! Como nuevo.",
                   "Reluciente. Mantén el café lejos.", "Listo. Salud."],
        breakTips: [
            "Mira algo a ~6 metros durante 20 segundos. Tus ojos lo agradecerán.",
            "Parpadea a propósito varias veces: ante la pantalla parpadeas la mitad.",
            "Sube los hombros hasta las orejas, cuenta tres, suelta.",
            "Mira por la ventana. Elige un punto lejano y enfócalo.",
            "Levántate, da unos pasos. Tu espalda lo recordará.",
            "Respira hondo: 4 segundos al inspirar, 6 al espirar.",
            "Gira las muñecas en ambos sentidos, abre y cierra los dedos.",
            "¿El brillo de la pantalla encaja con la habitación? Compruébalo.",
            "Bebe agua. Sí, ahora.",
            "Gira el cuello despacio de lado a lado. Sin forzar."
        ],
        breakDone: ["Descanso terminado, sigue donde lo dejaste.", "Ojos descansados. Vamos.", "Recargado. ¡Continúa!"]
    )
}
