import Foundation

extension TVStrings {
    static let japanese = TVStrings(
        tagline: "安心して Mac を拭こう。キーは預かっておきます。",
        tabCleaning: "掃除", tabBreak: "休憩",
        durationLabel: "掃除の長さ", themeLabel: "画面テーマ",
        startCleaning: "掃除を始める", cleaningInProgress: "掃除中…",
        previewButton: "プレビュー（ロックなし）",
        unlockHintMenu: "**esc** を %@ 秒長押しで解除。",
        settings: "設定…", quit: "終了",
        language: "言語", systemLanguage: "システムの言語（%@）",
        secondsChoice: "%d 秒",
        secondsChoiceOne: "1 秒",
        minutesChoice: "%d 分",
        minutesChoiceOne: "1 分",
        unlimited: "無制限",
        countdownHoursMinutes: "%d 時間 %02d 分",

        themeDarkShort: "ダーク", themeLightShort: "ライト", themeColorShort: "カラー",
        themeDarkLong: "ダーク（ホコリが一番見える）",
        themeLightLong: "ライト（指紋が一番見える）",
        themeColorLong: "カラフル",

        permissionTitle: "アクセシビリティの許可が必要です",
        permissionBody: "キーボードとトラックパッドをロックするには、システム設定 → プライバシーとセキュリティ → アクセシビリティ で Temizlik Vakti を許可してください。",
        permissionRequest: "許可を求める", permissionOpenSettings: "設定を開く",
        permissionRelaunch: "再起動",
        permissionStaleNote: "許可済みなのに警告が消えない場合はアプリを再起動してください。macOS が古い許可情報を更新するのはそのタイミングだけのことがあります。",
        permissionGranted: "アクセシビリティ許可あり",
        permissionMissing: "アクセシビリティ許可なし",

        unlockHold: "長押しで解除", unlockHolding: "そのまま…",
        lockFooterNote: "キーボードとトラックパッドをロック中 · アプリが終了すれば入力はすぐ戻ります",
        previewFooterNote: "プレビュー · 入力はロックされていません · 任意のキーまたはクリックで終了",
        unlimitedSession: "時間無制限のセッション",
        allClean: "ピカピカ！",
        perfectRun: "完璧 — キーに一度も触れませんでした",
        sessionSummary: "掃除時間: %@ · ブロックした入力: %d 回",

        eggParty: "隠しコマンド成立。パーティーモード！",
        eggAnnoyed: "はいはい！わかりましたって！",
        eggDizzy: "うわ、目が回る…",
        eggSleepy: "Zzz… 拭くのは任せた、ひと眠り。",
        eggCaps: "叫ばなくても聞こえてますよ。",
        eggSecret: "合言葉だ！スポンジに気に入られました。",

        breakTitle: "目の休憩", breakOver: "休憩終了",
        breakSnooze: "5 分後に", breakSkip: "休憩をスキップ",
        breakEscHint: "esc でもスキップできます",
        breakStrictHint: "厳格モード · キーボードとトラックパッドをロック中",
        breakStrictUnlock: "長押しで休憩をスキップ",
        breakToggle: "目の休憩リマインダー", breakWork: "作業", breakLength: "休憩",
        breakStrictMode: "厳格モード — 休憩中は入力をロック",
        breakSkipWhenIdle: "席を外しているときは休憩をスキップ",
        breakNow: "今すぐ休憩", breakPauseHour: "1 時間停止", breakResume: "再開",
        breakRuleNote: "20-20-20: 20 分ごとに、約 6 メートル先を 20 秒見る。",
        breakDisabled: "リマインダーはオフ",
        breakPaused: "停止中 — 残り %@", breakNext: "次の休憩: %@",
        breakScheduling: "予定を組んでいます…",

        settingsSession: "セッション", settingsAppearance: "外観", settingsGeneral: "一般",
        settingsDuration: "長さ", settingsPreroll: "開始前のカウントダウン: %d 秒",
        settingsUnlockHold: "解除に必要な esc の長押し: %@ 秒",
        settingsTheme: "テーマ", settingsShowMascot: "マスコットを表示",
        settingsSnark: "皮肉なひとこと", settingsBubbles: "シャボン玉",
        settingsHideCursor: "カーソルを隠す", settingsSounds: "効果音",
        settingsLaunchAtLogin: "ログイン時に起動", settingsRefresh: "再確認",
        settingsOpenSettings: "設定を開く",
        settingsEasterEggNote: "入力をロック中でも、マスコットはトラックパッドの動きを目で追いかけます。隠し要素もあります: 例の隠しコマンドを入力する、\"temiz\" と打つ、あるいはしばらく何も触らないでみてください。",
        settingsShortcutNote: "ショートカット: Control + Option + Command + C で掃除を開始します。電源ボタン、Touch ID、一部のハードウェアキーは macOS に保護されておりロックできません。アプリが終了すれば入力はすぐ戻ります。",
        settingsBreakSection: "目の休憩（20-20-20）",
        settingsBreakNote: "%d 分ごとに %d 秒の休憩画面が出ます。厳格モードがオフなら esc でスキップ、または 5 分後に延期できます。",

        snark: [
            "右下の角を飛ばさないで。見えてますよ。",
            "ちなみにキーボードの下のそのカスは 2019 年ものです。",
            "拭くのは画面です。輝度設定ではありません。",
            "トラックパッドに指紋のギャラリーができてますね。",
            "マイクロファイバークロスを使って。T シャツは布じゃない。",
            "画面に直接スプレーしないで。布に。お願いします。",
            "スペースキーの下には生態系があります。",
            "ガラスクリーナーではなく、精製水とマイクロファイバーで。",
            "通気口も忘れずに — ホコリ博物館です。",
            "その汚れ、M3 チップも恥ずかしがってます。",
            "次は天板のリンゴマーク。ここは光らせましょう。",
            "濡れ布ではなく湿らせた布。その差が保証です。"
        ],
        preroll: ["手を離して、ロックします…", "クロスの準備は？", "3…2…1…掃除の時間！"],
        blocked: ["無駄ですよ、ロック中です。", "そのキーは今お休み中。",
                  "押すのはやめて、拭くのを続けて。", "コンコン。誰もいません。",
                  "やってみた。ダメでした。クロスに戻りましょう。"],
        finished: ["ピカピカ。5 分くらい眺めていいですよ。", "これです！新品同様。",
                   "輝いてます。コーヒーは遠ざけて。", "完了。おつかれさま。"],
        breakTips: [
            "約 6 メートル先を 20 秒見てください。目が喜びます。",
            "意識して数回まばたきを。画面を見ていると回数が半分になります。",
            "肩を耳まで上げて、3 つ数えて、脱力。",
            "窓の外を見て、遠くの一点にピントを合わせて。",
            "立ち上がって数歩。背中が覚えています。",
            "深呼吸: 4 秒吸って、6 秒吐く。",
            "手首を両方向に回して、指を開いて閉じて。",
            "画面の明るさは部屋の明るさと合っていますか。",
            "水を飲みましょう。はい、今です。",
            "首をゆっくり左右に。無理はしないで。"
        ],
        breakDone: ["休憩終了、続きをどうぞ。", "目が休まりました。いきましょう。", "充電完了。続けて！"]
    )
}
