import Foundation

extension TVStrings {
    static let german = TVStrings(
        tagline: "Putz deinen Mac. Die Tasten warten solange.",
        tabCleaning: "Reinigung", tabBreak: "Pause",
        durationLabel: "Reinigungsdauer", themeLabel: "Bildschirmdesign",
        startCleaning: "Reinigung starten", cleaningInProgress: "Reinigung läuft…",
        previewButton: "Vorschau (ohne Sperre)",
        unlockHintMenu: "Zum Entsperren **esc** %@ s gedrückt halten.",
        settings: "Einstellungen…", quit: "Beenden",
        language: "Sprache", systemLanguage: "Systemsprache (%@)",

        secondsChoice: "%d Sekunden", minutesChoice: "%d Minuten", unlimited: "Ohne Limit",

        themeDarkShort: "Dunkel", themeLightShort: "Hell", themeColorShort: "Farbig",
        themeDarkLong: "Dunkel (zeigt Staub am besten)",
        themeLightLong: "Hell (zeigt Fingerabdrücke am besten)",
        themeColorLong: "Farbig",

        permissionTitle: "Bedienungshilfen-Zugriff nötig",
        permissionBody: "Um Tastatur und Trackpad zu sperren, erlaube Temizlik Vakti unter Systemeinstellungen → Datenschutz & Sicherheit → Bedienungshilfen.",
        permissionRequest: "Zugriff anfragen", permissionOpenSettings: "Einstellungen öffnen",
        permissionRelaunch: "Neu starten",
        permissionStaleNote: "Wenn du den Zugriff erteilt hast und diese Warnung bleibt, starte die App neu — macOS aktualisiert einen veralteten Eintrag manchmal erst dann.",
        permissionGranted: "Bedienungshilfen-Zugriff erteilt",
        permissionMissing: "Kein Bedienungshilfen-Zugriff",

        unlockHold: "Zum Entsperren halten", unlockHolding: "Weiter halten…",
        lockFooterNote: "Tastatur und Trackpad gesperrt · Beim Beenden der App kommt die Eingabe sofort zurück",
        unlimitedSession: "Sitzung ohne Zeitlimit",
        allClean: "Blitzblank!",
        perfectRun: "Perfekter Durchgang — keine einzige Taste berührt",
        sessionSummary: "Reinigungsdauer: %@ · blockierte Eingaben: %d",

        eggParty: "Cheat-Code akzeptiert. Partymodus!",
        eggAnnoyed: "Ja, ja! Ich hab's verstanden!",
        eggDizzy: "Okay, mir wird schwindelig…",
        eggSleepy: "Zzz… putz du, ich mach ein Nickerchen.",
        eggCaps: "Du musst nicht schreien, ich bin hier.",
        eggSecret: "Zauberwort! Der Schwamm mag dich.",

        breakTitle: "Augenpause", breakOver: "Pause vorbei",
        breakSnooze: "5 Min später", breakSkip: "Pause überspringen",
        breakEscHint: "esc überspringt die Pause ebenfalls",
        breakStrictHint: "Strenger Modus · Tastatur und Trackpad gesperrt",
        breakStrictUnlock: "Halten, um die Pause zu überspringen",
        breakToggle: "Augenpausen-Erinnerung", breakWork: "Arbeit", breakLength: "Pause",
        breakStrictMode: "Strenger Modus — Eingabe während der Pause sperren",
        breakSkipWhenIdle: "Pause überspringen, wenn ich nicht da bin",
        breakNow: "Jetzt Pause", breakPauseHour: "1 Std pausieren", breakResume: "Fortsetzen",
        breakRuleNote: "20-20-20: alle 20 Minuten 20 Sekunden lang auf etwa 6 Meter Entfernung schauen.",
        breakDisabled: "Erinnerung aus",
        breakPaused: "Pausiert — noch %@", breakNext: "Nächste Pause: %@",
        breakScheduling: "Wird geplant…",

        settingsSession: "Sitzung", settingsAppearance: "Darstellung", settingsGeneral: "Allgemein",
        settingsDuration: "Dauer", settingsPreroll: "Countdown zu Beginn: %d s",
        settingsUnlockHold: "esc zum Entsperren halten: %@ s",
        settingsTheme: "Design", settingsShowMascot: "Maskottchen zeigen",
        settingsSnark: "Freche Kommentare", settingsBubbles: "Seifenblasen",
        settingsHideCursor: "Zeiger ausblenden", settingsSounds: "Soundeffekte",
        settingsLaunchAtLogin: "Beim Anmelden starten", settingsRefresh: "Aktualisieren",
        settingsOpenSettings: "Einstellungen öffnen",
        settingsEasterEggNote: "Auch bei gesperrter Eingabe verfolgt das Maskottchen deine Trackpad-Bewegungen mit den Augen. Es gibt versteckte Tricks: gib den klassischen Cheat-Code ein, tippe \"temiz\", oder rühre eine Weile nichts an.",
        settingsShortcutNote: "Kurzbefehl: Control + Option + Command + C startet die Reinigung. Ein-/Ausschalter, Touch ID und einige Hardwaretasten sind von macOS geschützt und lassen sich nicht sperren. Beim Beenden der App kommt die Eingabe sofort zurück.",
        settingsBreakSection: "Augenpause (20-20-20)",
        settingsBreakNote: "Alle %d Minuten erscheint ein %d Sekunden langer Pausenbildschirm. Ohne strengen Modus kannst du ihn mit esc überspringen oder 5 Minuten verschieben.",

        snark: [
            "Die Ecke rechts unten nicht auslassen. Ich sehe das.",
            "Der Krümel unter der Tastatur ist übrigens von 2019.",
            "Wisch den Bildschirm, nicht die Helligkeitseinstellung.",
            "Auf dem Trackpad hast du eine ganze Fingerabdruck-Galerie kuratiert.",
            "Nimm ein Mikrofasertuch. Dein T-Shirt ist kein Tuch.",
            "Sprüh nie direkt auf den Bildschirm. Auf das Tuch. Bitte.",
            "Unter der Leertaste lebt ein ganzes Ökosystem.",
            "Nicht Glasreiniger: destilliertes Wasser und Mikrofaser.",
            "Vergiss die Lüftungsschlitze nicht — das Staubmuseum.",
            "Sogar dein M3-Chip schämt sich für diesen Dreck.",
            "Jetzt noch das Apple-Logo auf dem Deckel. Das muss glänzen.",
            "Feuchtes Tuch, nicht nasses. Der Unterschied ist deine Garantie."
        ],
        preroll: ["Hände weg, ich sperre…", "Tuch bereit?", "Drei… zwei… eins… Putzzeit!"],
        blocked: ["Netter Versuch, gesperrt.", "Diese Taste hat gerade Urlaub.",
                  "Hör auf zu tippen, fang an zu wischen.", "Klopf klopf. Niemand da.",
                  "Versucht. Gescheitert. Zurück zum Tuch."],
        finished: ["Blitzblank. Du darfst fünf Minuten hinstarren.", "Da ist es! Wie neu.",
                   "Glänzt. Halt den Kaffee fern.", "Fertig. Wohl bekomm's."],
        breakTips: [
            "Schau 20 Sekunden auf etwas in ~6 Metern Entfernung. Deine Augen danken es.",
            "Blinzle bewusst ein paar Mal — vor dem Bildschirm blinzelst du halb so oft.",
            "Zieh die Schultern zu den Ohren, zähl bis drei, loslassen.",
            "Schau aus dem Fenster. Such dir einen fernen Punkt.",
            "Steh auf, geh ein paar Schritte. Dein Rücken merkt sich das.",
            "Tief atmen: 4 Sekunden ein, 6 Sekunden aus.",
            "Kreise die Handgelenke in beide Richtungen, Finger öffnen und schließen.",
            "Passt die Bildschirmhelligkeit zum Raum? Prüf es.",
            "Trink Wasser. Ja, jetzt.",
            "Dreh den Kopf langsam hin und her. Ohne Zwang."
        ],
        breakDone: ["Pause vorbei, weiter geht's.", "Augen erholt. Los.", "Aufgeladen. Weitermachen!"]
    )
}
