import Foundation

extension TVStrings {
    static let french = TVStrings(
        tagline: "Nettoie ton Mac. Les touches attendront.",
        tabCleaning: "Nettoyage", tabBreak: "Pause",
        durationLabel: "Durée du nettoyage", themeLabel: "Thème de l'écran",
        startCleaning: "Commencer le nettoyage", cleaningInProgress: "Nettoyage en cours…",
        previewButton: "Aperçu (sans verrouiller)",
        unlockHintMenu: "Maintiens **esc** %@ s pour déverrouiller.",
        settings: "Réglages…", quit: "Quitter",
        language: "Langue", systemLanguage: "Langue du système (%@)",
        secondsChoice: "%d secondes",
        secondsChoiceOne: "1 seconde",
        minutesChoice: "%d minutes",
        minutesChoiceOne: "1 minute",
        unlimited: "Sans limite",
        countdownHoursMinutes: "%d h %02d min",

        themeDarkShort: "Sombre", themeLightShort: "Clair", themeColorShort: "Couleur",
        themeDarkLong: "Sombre (révèle la poussière)",
        themeLightLong: "Clair (révèle les traces de doigts)",
        themeColorLong: "Coloré",

        permissionTitle: "Autorisation d'accessibilité requise",
        permissionBody: "Pour verrouiller le clavier et le trackpad, autorise Temizlik Vakti dans Réglages Système → Confidentialité et sécurité → Accessibilité.",
        permissionRequest: "Demander l'accès", permissionOpenSettings: "Ouvrir les réglages",
        permissionRelaunch: "Relancer",
        permissionStaleNote: "Si tu as donné l'autorisation et que l'avertissement reste, relance l'app : macOS ne rafraîchit parfois l'ancien enregistrement qu'à ce moment-là.",
        permissionGranted: "Accès à l'accessibilité accordé",
        permissionMissing: "Pas d'accès à l'accessibilité",

        unlockHold: "Maintiens pour déverrouiller", unlockHolding: "Continue…",
        lockFooterNote: "Clavier et trackpad verrouillés · Si l'app se ferme, la saisie revient aussitôt",
        unlimitedSession: "Session sans limite",
        allClean: "Impeccable !",
        perfectRun: "Parcours parfait — aucune touche effleurée",
        sessionSummary: "Durée du nettoyage : %@ · saisies bloquées : %d",

        eggParty: "Code de triche accepté. Mode fête !",
        eggAnnoyed: "D'accord, d'accord ! J'ai compris !",
        eggDizzy: "Bon, j'ai la tête qui tourne…",
        eggSleepy: "Zzz… nettoie, je fais la sieste.",
        eggCaps: "Pas besoin de crier, je suis là.",
        eggSecret: "Le mot magique ! L'éponge t'adore.",

        breakTitle: "Pause visuelle", breakOver: "Pause terminée",
        breakSnooze: "Reporter 5 min", breakSkip: "Passer la pause",
        breakEscHint: "esc passe aussi la pause",
        breakStrictHint: "Mode strict · clavier et trackpad verrouillés",
        breakStrictUnlock: "Maintiens pour passer la pause",
        breakToggle: "Rappel de pause visuelle", breakWork: "Travail", breakLength: "Pause",
        breakStrictMode: "Mode strict — verrouiller la saisie pendant la pause",
        breakSkipWhenIdle: "Passer la pause si je ne suis pas là",
        breakNow: "Pause maintenant", breakPauseHour: "Suspendre 1 h", breakResume: "Reprendre",
        breakRuleNote: "20-20-20 : toutes les 20 minutes, regarde à ~6 mètres pendant 20 secondes.",
        breakDisabled: "Rappel désactivé",
        breakPaused: "Suspendu — %@ restant", breakNext: "Prochaine pause : %@",
        breakScheduling: "Planification…",

        settingsSession: "Session", settingsAppearance: "Apparence", settingsGeneral: "Général",
        settingsDuration: "Durée", settingsPreroll: "Compte à rebours initial : %d s",
        settingsUnlockHold: "Maintien de esc pour déverrouiller : %@ s",
        settingsTheme: "Thème", settingsShowMascot: "Afficher la mascotte",
        settingsSnark: "Remarques taquines", settingsBubbles: "Bulles de savon",
        settingsHideCursor: "Masquer le curseur", settingsSounds: "Effets sonores",
        settingsLaunchAtLogin: "Ouvrir à la session", settingsRefresh: "Actualiser",
        settingsOpenSettings: "Ouvrir les réglages",
        settingsEasterEggNote: "Même quand la saisie est verrouillée, la mascotte suit tes mouvements de trackpad des yeux. Il y a des surprises : entre le code de triche classique, tape \"temiz\", ou ne touche à rien pendant un moment.",
        settingsShortcutNote: "Raccourci : Contrôle + Option + Commande + C lance le nettoyage. Le bouton d'alimentation, Touch ID et certaines touches matérielles sont protégés par macOS et ne peuvent pas être verrouillés. Si l'app se ferme, la saisie revient aussitôt.",
        settingsBreakSection: "Pause visuelle (20-20-20)",
        settingsBreakNote: "Toutes les %d minutes, un écran de pause de %d secondes s'affiche. Sans le mode strict, tu peux la passer avec esc ou la reporter de 5 minutes.",

        snark: [
            "Ne saute pas le coin en bas à droite. Je le vois.",
            "La miette sous le clavier date de 2019, au fait.",
            "Essuie l'écran, pas le réglage de luminosité.",
            "Tu as constitué une belle galerie d'empreintes sur ce trackpad.",
            "Prends un chiffon microfibre. Ton t-shirt n'en est pas un.",
            "Ne vaporise jamais directement sur l'écran. Sur le chiffon. S'il te plaît.",
            "Il y a tout un écosystème sous la barre d'espace.",
            "Pas de nettoyant à vitres : eau distillée et microfibre.",
            "N'oublie pas les grilles d'aération — le musée de la poussière.",
            "Même ta puce M3 a honte de cette saleté.",
            "Et maintenant le logo Apple sur le capot. Il doit briller.",
            "Chiffon humide, pas mouillé. La différence, c'est ta garantie."
        ],
        preroll: ["Retire les mains, je verrouille…", "Chiffon prêt ?", "Trois… deux… un… on nettoie !"],
        blocked: ["Bien essayé, c'est verrouillé.", "Cette touche est en vacances.",
                  "Arrête d'appuyer, continue d'essuyer.", "Toc toc. Personne.",
                  "Tu as essayé. Raté. Retour au chiffon."],
        finished: ["Impeccable. Tu peux l'admirer cinq minutes.", "Voilà ! Comme neuf.",
                   "Ça brille. Éloigne le café.", "Terminé. À la tienne."],
        breakTips: [
            "Regarde à ~6 mètres pendant 20 secondes. Tes yeux te remercieront.",
            "Cligne des yeux volontairement — devant un écran, tu clignes deux fois moins.",
            "Monte les épaules vers les oreilles, compte jusqu'à trois, relâche.",
            "Regarde par la fenêtre. Choisis un point lointain.",
            "Lève-toi, fais quelques pas. Ton dos s'en souviendra.",
            "Respire : 4 secondes à l'inspiration, 6 à l'expiration.",
            "Fais tourner tes poignets, ouvre et ferme les doigts.",
            "La luminosité de l'écran correspond-elle à la pièce ? Vérifie.",
            "Bois de l'eau. Oui, maintenant.",
            "Tourne lentement la tête de gauche à droite. Sans forcer."
        ],
        breakDone: ["Pause terminée, reprends où tu en étais.", "Yeux reposés. C'est reparti.", "Rechargé. Continue !"]
    )
}
