import Foundation

extension TVStrings {
    static let chinese = TVStrings(
        tagline: "安心擦你的 Mac，按键交给我。",
        tabCleaning: "清洁", tabBreak: "休息",
        durationLabel: "清洁时长", themeLabel: "屏幕主题",
        startCleaning: "开始清洁", cleaningInProgress: "正在清洁…",
        previewButton: "预览（不锁定）",
        unlockHintMenu: "长按 **esc** %@ 秒解锁。",
        settings: "设置…", quit: "退出",
        language: "语言", systemLanguage: "系统语言（%@）",
        secondsChoice: "%d 秒",
        secondsChoiceOne: "1 秒",
        minutesChoice: "%d 分钟",
        minutesChoiceOne: "1 分钟",
        unlimited: "不限时",
        countdownHoursMinutes: "%d 小时 %02d 分",

        themeDarkShort: "深色", themeLightShort: "浅色", themeColorShort: "彩色",
        themeDarkLong: "深色（最容易看清灰尘）",
        themeLightLong: "浅色（最容易看清指纹）",
        themeColorLong: "彩色",

        permissionTitle: "需要辅助功能权限",
        permissionBody: "要锁定键盘和触控板，请在「系统设置 → 隐私与安全性 → 辅助功能」中允许 Temizlik Vakti。",
        permissionRequest: "请求权限", permissionOpenSettings: "打开设置",
        permissionRelaunch: "重新启动",
        permissionStaleNote: "如果已经授权但提示还在，请重启这个 App —— macOS 有时只有这样才会刷新过期的权限记录。",
        permissionGranted: "已获得辅助功能权限",
        permissionMissing: "没有辅助功能权限",

        unlockHold: "长按解锁", unlockHolding: "别松手…",
        lockFooterNote: "键盘和触控板已锁定 · App 一旦退出，输入立即恢复",
        unlimitedSession: "不限时会话",
        allClean: "干干净净！",
        perfectRun: "完美一轮 —— 一个键都没碰",
        sessionSummary: "清洁用时：%@ · 拦截输入：%d 次",

        eggParty: "秘技代码通过。派对模式！",
        eggAnnoyed: "好了好了！我知道了！",
        eggDizzy: "好吧，我有点晕了…",
        eggSleepy: "呼…你擦，我睡一会儿。",
        eggCaps: "不用喊，我就在这儿。",
        eggSecret: "说对暗号了！海绵喜欢你。",

        breakTitle: "护眼休息", breakOver: "休息结束",
        breakSnooze: "延后 5 分钟", breakSkip: "跳过休息",
        breakEscHint: "按 esc 也可以跳过",
        breakStrictHint: "严格模式 · 键盘和触控板已锁定",
        breakStrictUnlock: "长按以跳过休息",
        breakToggle: "护眼休息提醒", breakWork: "工作", breakLength: "休息",
        breakStrictMode: "严格模式 —— 休息期间锁定输入",
        breakSkipWhenIdle: "我不在电脑前时跳过休息",
        breakNow: "立即休息", breakPauseHour: "暂停 1 小时", breakResume: "继续",
        breakRuleNote: "20-20-20：每 20 分钟，看 6 米外的东西 20 秒。",
        breakDisabled: "提醒已关闭",
        breakPaused: "已暂停 —— 还剩 %@", breakNext: "下次休息：%@",
        breakScheduling: "安排中…",

        settingsSession: "会话", settingsAppearance: "外观", settingsGeneral: "通用",
        settingsDuration: "时长", settingsPreroll: "开始倒计时：%d 秒",
        settingsUnlockHold: "长按 esc 解锁：%@ 秒",
        settingsTheme: "主题", settingsShowMascot: "显示吉祥物",
        settingsSnark: "毒舌评论", settingsBubbles: "肥皂泡",
        settingsHideCursor: "隐藏光标", settingsSounds: "音效",
        settingsLaunchAtLogin: "登录时启动", settingsRefresh: "刷新",
        settingsOpenSettings: "打开设置",
        settingsEasterEggNote: "即使输入被锁定，吉祥物也会用眼睛追踪你在触控板上的动作。还有一些隐藏玩法：输入经典秘技代码、打出 \"temiz\"，或者一会儿什么都别碰。",
        settingsShortcutNote: "快捷键：Control + Option + Command + C 开始清洁。电源键、触控 ID 和部分硬件按键由 macOS 保护，无法锁定。App 一旦退出，输入立即恢复。",
        settingsBreakSection: "护眼休息（20-20-20）",
        settingsBreakNote: "每 %d 分钟会出现 %d 秒的休息画面。关闭严格模式时，可以按 esc 跳过或延后 5 分钟。",

        snark: [
            "右下角别漏了，我看得见。",
            "顺便一提，键盘下面那颗碎屑是 2019 年的。",
            "擦的是屏幕，不是亮度设置。",
            "你在触控板上办了个指纹展览。",
            "用超细纤维布。你的 T 恤不算布。",
            "别直接往屏幕上喷。喷在布上，拜托。",
            "空格键下面住着一整个生态系统。",
            "别用玻璃水：蒸馏水加超细纤维布。",
            "别忘了散热孔 —— 灰尘博物馆。",
            "连你的 M3 芯片都替这些灰尘不好意思。",
            "接着是盖子上的苹果标志。那得发亮。",
            "湿布，不是滴水的布。这个区别叫保修。"
        ],
        preroll: ["手拿开，我要锁了…", "布准备好了吗？", "三…二…一…开始清洁！"],
        blocked: ["白费劲，锁着呢。", "那个键正在休假。",
                  "别按了，继续擦。", "咚咚。没人应门。",
                  "试过了，没用。回去擦吧。"],
        finished: ["干干净净。可以盯着看五分钟了。", "就是这样！跟新的一样。",
                   "锃亮。咖啡离远点。", "搞定。干杯。"],
        breakTips: [
            "看 6 米外的东西 20 秒，眼睛会感谢你。",
            "有意识地眨几次眼 —— 盯着屏幕时眨眼频率会减半。",
            "把肩膀往耳朵方向提，数三下，放松。",
            "看看窗外，挑一个远处的点聚焦。",
            "站起来走几步，你的背会记得这份好。",
            "深呼吸：吸气 4 秒，呼气 6 秒。",
            "手腕双向转动，手指张开再握紧。",
            "屏幕亮度和房间光线匹配吗？检查一下。",
            "喝点水。对，现在就喝。",
            "慢慢左右转动脖子，别用力。"
        ],
        breakDone: ["休息结束，接着刚才继续。", "眼睛歇过来了，开工。", "电量回满。继续！"]
    )
}
