import Foundation

extension TVStrings {
    static let portuguese = TVStrings(
        tagline: "Limpe o seu Mac. As teclas podem esperar.",
        tabCleaning: "Limpeza", tabBreak: "Pausa",
        durationLabel: "Duração da limpeza", themeLabel: "Tema da tela",
        startCleaning: "Começar limpeza", cleaningInProgress: "Limpeza em andamento…",
        previewButton: "Pré-visualizar (sem bloquear)",
        unlockHintMenu: "Segure **esc** por %@ s para desbloquear.",
        settings: "Ajustes…", quit: "Sair",
        language: "Idioma", systemLanguage: "Idioma do sistema (%@)",
        secondsChoice: "%d segundos",
        secondsChoiceOne: "1 segundo",
        minutesChoice: "%d minutos",
        minutesChoiceOne: "1 minuto",
        unlimited: "Sem limite",
        countdownHoursMinutes: "%d h %02d min",

        themeDarkShort: "Escuro", themeLightShort: "Claro", themeColorShort: "Cor",
        themeDarkLong: "Escuro (mostra melhor a poeira)",
        themeLightLong: "Claro (mostra melhor as digitais)",
        themeColorLong: "Colorido",

        permissionTitle: "É preciso permissão de acessibilidade",
        permissionBody: "Para bloquear o teclado e o trackpad, autorize o Temizlik Vakti em Ajustes do Sistema → Privacidade e Segurança → Acessibilidade.",
        permissionRequest: "Pedir acesso", permissionOpenSettings: "Abrir Ajustes",
        permissionRelaunch: "Reabrir app",
        permissionStaleNote: "Se você já concedeu e o aviso continua, reabra o app: às vezes o macOS só então atualiza um registro de permissão antigo.",
        permissionGranted: "Acesso de acessibilidade concedido",
        permissionMissing: "Sem acesso de acessibilidade",

        unlockHold: "Segure para desbloquear", unlockHolding: "Não solte…",
        lockFooterNote: "Teclado e trackpad bloqueados · Se o app fechar, a entrada volta na hora",
        previewFooterNote: "PRÉ-VISUALIZAÇÃO · A entrada NÃO está bloqueada · Pressione uma tecla ou clique para sair",
        unlimitedSession: "Sessão sem limite",
        allClean: "Impecável!",
        perfectRun: "Rodada perfeita — você não tocou em nenhuma tecla",
        sessionSummary: "Tempo de limpeza: %@ · entradas bloqueadas: %d",

        eggParty: "Código secreto aceito. Modo festa!",
        eggAnnoyed: "Tá bom, tá bom! Já entendi!",
        eggDizzy: "Ok, fiquei tonto…",
        eggSleepy: "Zzz… você limpa, eu tiro um cochilo.",
        eggCaps: "Não precisa gritar, estou aqui.",
        eggSecret: "A palavra mágica! A esponja gostou de você.",

        breakTitle: "Pausa para os olhos", breakOver: "Pausa encerrada",
        breakSnooze: "Adiar 5 min", breakSkip: "Pular pausa",
        breakEscHint: "esc também pula a pausa",
        breakStrictHint: "Modo rígido · teclado e trackpad bloqueados",
        breakStrictUnlock: "Segure para pular a pausa",
        breakToggle: "Lembrete de pausa para os olhos", breakWork: "Trabalho", breakLength: "Pausa",
        breakStrictMode: "Modo rígido — bloquear a entrada durante a pausa",
        breakSkipWhenIdle: "Pular a pausa quando eu não estiver aqui",
        breakNow: "Pausar agora", breakPauseHour: "Suspender 1 h", breakResume: "Retomar",
        breakRuleNote: "20-20-20: a cada 20 minutos, olhe a ~6 metros por 20 segundos.",
        breakDisabled: "Lembrete desativado",
        breakPaused: "Suspenso — faltam %@", breakNext: "Próxima pausa: %@",
        breakScheduling: "Agendando…",

        settingsSession: "Sessão", settingsAppearance: "Aparência", settingsGeneral: "Geral",
        settingsDuration: "Duração", settingsPreroll: "Contagem inicial: %d s",
        settingsUnlockHold: "Segurar esc para desbloquear: %@ s",
        settingsTheme: "Tema", settingsShowMascot: "Mostrar o mascote",
        settingsSnark: "Comentários irônicos", settingsBubbles: "Bolhas de sabão",
        settingsHideCursor: "Ocultar o cursor", settingsSounds: "Efeitos sonoros",
        settingsLaunchAtLogin: "Abrir ao iniciar sessão", settingsRefresh: "Atualizar",
        settingsOpenSettings: "Abrir Ajustes",
        settingsEasterEggNote: "Mesmo com a entrada bloqueada, o mascote acompanha os movimentos do trackpad com os olhos. Há truques escondidos: digite o código clássico, escreva \"temiz\", ou não toque em nada por um tempo.",
        settingsShortcutNote: "Atalho: Control + Option + Command + C inicia a limpeza. O botão de energia, o Touch ID e algumas teclas de hardware são protegidos pelo macOS e não podem ser bloqueados. Se o app fechar, a entrada volta na hora.",
        settingsBreakSection: "Pausa para os olhos (20-20-20)",
        settingsBreakNote: "A cada %d minutos aparece uma tela de pausa de %d segundos. Com o modo rígido desligado, você pode pular com esc ou adiar 5 minutos.",
        onboardWelcomeTitle: "Boas-vindas ao Temizlik Vakti",
        onboardWelcomeBody: "Bloqueia o teclado enquanto você limpa o Mac, para não apertar nada sem querer. Inicie pelo ícone ✨ na barra de menus.",
        onboardPermissionTitle: "Só uma permissão",
        onboardPermissionBody: "Bloquear teclado e trackpad exige acesso de Acessibilidade. Você pode conceder abaixo; o app não mexe em mais nada.",
        onboardBreakTitle: "E uma pausa para os olhos",
        onboardBreakBody: "Se quiser, ele lembra de uma pausa de 20 segundos a cada 20 minutos. A regra 20-20-20: olhe a 6 metros.",
        onboardNext: "Continuar",
        onboardDone: "Começar",
        onboardSkip: "Pular",
        breakWarningTitle: "Pausa para os olhos em %d s",
        breakWarningStartNow: "Começar agora",
        breakWarningLater: "Em 5 min",
        statsTitle: "Estatísticas",
        statsSessions: "Sessões de limpeza",
        statsTotalTime: "Tempo total",
        statsBlockedInputs: "Entradas bloqueadas",
        statsPerfectRuns: "Rodadas perfeitas",
        statsBreaks: "Pausas feitas",
        statsReset: "Zerar",
        statsEmpty: "Ainda sem dados — aparecem após a primeira limpeza.",
        settingsVersion: "Versão %@",


        snark: [
            "Não pule o canto inferior direito. Estou vendo.",
            "Aliás, aquela migalha sob o teclado é de 2019.",
            "Limpe a tela, não o ajuste de brilho.",
            "Você montou uma bela galeria de digitais nesse trackpad.",
            "Use um pano de microfibra. Sua camiseta não é um pano.",
            "Nunca borrife direto na tela. No pano. Por favor.",
            "Embaixo da barra de espaço existe um ecossistema inteiro.",
            "Nada de limpa-vidros: água destilada e microfibra.",
            "Não esqueça as saídas de ar — o museu da poeira.",
            "Até o seu chip M3 ficou com vergonha dessa sujeira.",
            "Agora o logo da Apple na tampa. Tem que brilhar.",
            "Pano úmido, não molhado. A diferença é a sua garantia."
        ],
        preroll: ["Tire as mãos, vou bloquear…", "Pano pronto?", "Três… dois… um… hora da limpeza!"],
        blocked: ["Boa tentativa, está bloqueado.", "Essa tecla está de férias.",
                  "Pare de apertar, continue limpando.", "Toc toc. Não tem ninguém.",
                  "Tentou. Não rolou. Volte para o pano."],
        finished: ["Impecável. Pode ficar admirando por cinco minutos.", "É isso! Como novo.",
                   "Brilhando. Mantenha o café longe.", "Pronto. Saúde."],
        breakTips: [
            "Olhe para algo a ~6 metros por 20 segundos. Seus olhos agradecem.",
            "Pisque de propósito algumas vezes — diante da tela você pisca pela metade.",
            "Levante os ombros até as orelhas, conte até três, solte.",
            "Olhe pela janela. Escolha um ponto distante e foque nele.",
            "Levante-se, dê alguns passos. Sua coluna lembra disso.",
            "Respire fundo: 4 segundos inspirando, 6 expirando.",
            "Gire os punhos nos dois sentidos, abra e feche os dedos.",
            "O brilho da tela combina com a luz do ambiente? Confira.",
            "Beba água. Sim, agora.",
            "Gire o pescoço devagar de um lado para o outro. Sem forçar."
        ],
        breakDone: ["Pausa encerrada, continue de onde parou.", "Olhos descansados. Vamos lá.", "Recarregado. Siga em frente!"]
    )
}
