import Foundation

extension TVStrings {
    static let english = TVStrings(
        tagline: "Wipe your Mac. The keys can wait.",
        tabCleaning: "Cleaning",
        tabBreak: "Break",
        durationLabel: "Cleaning time",
        themeLabel: "Screen theme",
        startCleaning: "Start Cleaning",
        cleaningInProgress: "Cleaning in progress…",
        previewButton: "Preview (no lock)",
        unlockHintMenu: "Hold **esc** for %@ s to unlock.",
        settings: "Settings…",
        quit: "Quit",
        language: "Language",
        systemLanguage: "System language (%@)",
        secondsChoice: "%d seconds",
        secondsChoiceOne: "1 second",
        minutesChoice: "%d minutes",
        minutesChoiceOne: "1 minute",
        unlimited: "No limit",
        countdownHoursMinutes: "%dh %02dm",

        themeDarkShort: "Dark",
        themeLightShort: "Light",
        themeColorShort: "Color",
        themeDarkLong: "Dark (shows dust best)",
        themeLightLong: "Light (shows smudges best)",
        themeColorLong: "Colorful",

        permissionTitle: "Accessibility permission required",
        permissionBody: "To lock the keyboard and trackpad, allow Temizlik Vakti under System Settings → Privacy & Security → Accessibility.",
        permissionRequest: "Request access",
        permissionOpenSettings: "Open Settings",
        permissionRelaunch: "Relaunch",
        permissionStaleNote: "If you granted it and this warning stays, relaunch the app — macOS sometimes only refreshes a stale permission record then.",
        permissionGranted: "Accessibility access granted",
        permissionMissing: "No accessibility access",

        unlockHold: "Hold to unlock",
        unlockHolding: "Keep holding…",
        lockFooterNote: "Keyboard and trackpad locked · Input returns instantly if the app quits",
        previewFooterNote: "PREVIEW · Input is NOT locked · Press any key or click to exit",
        unlimitedSession: "Open-ended session",
        allClean: "Spotless!",
        perfectRun: "Perfect run — you never touched a key",
        sessionSummary: "Cleaning time: %@ · blocked input: %d",

        eggParty: "Cheat code accepted. Party mode!",
        eggAnnoyed: "All right, all right! I get it!",
        eggDizzy: "Okay, now I'm dizzy…",
        eggSleepy: "Zzz… you clean, I'll nap.",
        eggCaps: "No need to shout, I'm right here.",
        eggSecret: "Magic word! The sponge likes you.",

        breakTitle: "Eye Break",
        breakOver: "Break over",
        breakSnooze: "Snooze 5 min",
        breakSkip: "Skip break",
        breakEscHint: "esc also skips the break",
        breakStrictHint: "Strict mode on · keyboard and trackpad locked",
        breakStrictUnlock: "Hold to skip the break",
        breakToggle: "Eye break reminder",
        breakWork: "Work",
        breakLength: "Break",
        breakStrictMode: "Strict mode — lock input during the break",
        breakSkipWhenIdle: "Skip the break when I'm away",
        breakNow: "Break now",
        breakPauseHour: "Pause 1 h",
        breakResume: "Resume",
        breakRuleNote: "20-20-20: every 20 minutes, look at something ~6 metres away for 20 seconds.",
        breakDisabled: "Reminder off",
        breakPaused: "Paused — %@ left",
        breakNext: "Next break: %@",
        breakScheduling: "Scheduling…",

        settingsSession: "Session",
        settingsAppearance: "Appearance",
        settingsGeneral: "General",
        settingsDuration: "Duration",
        settingsPreroll: "Start countdown: %d s",
        settingsUnlockHold: "Hold esc to unlock: %@ s",
        settingsTheme: "Theme",
        settingsShowMascot: "Show mascot",
        settingsSnark: "Snarky remarks",
        settingsBubbles: "Soap bubbles",
        settingsHideCursor: "Hide the cursor",
        settingsSounds: "Sound effects",
        settingsLaunchAtLogin: "Launch at login",
        settingsRefresh: "Refresh",
        settingsOpenSettings: "Open Settings",
        settingsEasterEggNote: "Even while input is locked, the mascot watches your trackpad and follows you with its eyes. There are hidden tricks: enter the classic cheat code, type \"temiz\", or touch nothing for a while and see what happens.",
        settingsShortcutNote: "Shortcut: Control + Option + Command + C starts a cleaning session. The power button, Touch ID and some hardware keys are protected by macOS and cannot be locked. If the app quits, input returns instantly.",
        settingsBreakSection: "Eye break (20-20-20)",
        settingsBreakNote: "Every %d minutes a %d second break screen appears. With strict mode off you can skip it with esc or snooze it for 5 minutes.",

        snark: [
            "Don't skip that bottom-right corner. I can see it.",
            "That crumb under your keyboard is from 2019, by the way.",
            "Wipe the screen, not the brightness setting.",
            "You've curated quite the fingerprint gallery on that trackpad.",
            "Use a microfibre cloth. Your t-shirt is not a cloth.",
            "Never spray liquid straight onto the screen. Spray the cloth. Please.",
            "There's an entire ecosystem under the space bar.",
            "You hit Enter 4,312 times today. Give it some love.",
            "That grease spot… what did you have for breakfast?",
            "Don't forget the vents — the dust museum.",
            "The gap by the hinge. Yes, that one.",
            "Even your M3 chip is embarrassed by this.",
            "You're doing great, by the way. Kidding — look to the left.",
            "Not glass cleaner: distilled water and microfibre.",
            "That dot might be a dead pixel, not dust. Joking. Probably.",
            "Wipe around the ports too, but keep liquids away.",
            "Turn the keyboard over and shake gently. Gently, I said.",
            "The bottom case is part of your Mac too.",
            "Now the Apple logo on the lid. It should shine.",
            "Compressed air between the keys — but not from point blank.",
            "Saying it plainly: the edge of your caps lock is still filthy.",
            "Pressing keys does nothing right now. Relax.",
            "After this, try not to spill coffee on it. Deal?",
            "Wipe in soft horizontal strokes, not circles.",
            "When you do the trackpad, include the edges.",
            "If you're allergic to dust, a mask would've been smart.",
            "You wipe, I count dust. 4,891… 4,892…",
            "Leave the screws alone. Warranties are a thing.",
            "The tip of your charging cable has seen things.",
            "Shall we put the next clean-up in your calendar?",
            "Damp cloth, not wet cloth. The difference is your warranty.",
            "That scratch on the screen is not my fault.",
            "It took real dedication to collect this much grime.",
            "I turned off the keyboard backlight — the dirt shows better.",
            "Speaker grilles: the final frontier for explorers.",
            "Clean the camera lens too, you look foggy in meetings.",
            "This break is doing you good as well, admit it.",
            "Almost done. Or not. You set the timer.",
            "Keep alcohol under 70%, or the coating suffers.",
            "And that corner. Always the same corner."
        ],
        preroll: [
            "Hands off, locking now…",
            "Cloth ready?",
            "Three… two… one… cleaning time!"
        ],
        blocked: [
            "Nice try, it's locked.",
            "That key is on holiday right now.",
            "Stop pressing, start wiping.",
            "Knock knock. Nobody home.",
            "You tried. It didn't work. Back to the cloth."
        ],
        finished: [
            "Spotless. Feel free to stare at it for five minutes.",
            "There it is! Good as new.",
            "Gleaming. Keep the coffee away.",
            "Done. Cheers."
        ],
        breakTips: [
            "Look at something ~6 metres away for 20 seconds. Your eyes will thank you.",
            "Blink deliberately a few times — staring at a screen halves your blink rate.",
            "Pull your shoulders up to your ears, count to three, release.",
            "Look out of the window. Pick a distant point and focus on it.",
            "Stand up, take a few steps. Your back remembers.",
            "Deep breath: in for 4 seconds, out for 6.",
            "Rotate your wrists both ways, open and close your fingers.",
            "Does your screen brightness match the room? Check.",
            "Drink some water. Yes, now.",
            "Turn your neck slowly side to side. No forcing.",
            "Close your eyes for 10 seconds and just let them rest.",
            "Fix your posture: feet on the floor, screen at eye level."
        ],
        breakDone: [
            "Break's over, back where you left off.",
            "Eyes rested. Off you go.",
            "That's it, back to work.",
            "Recharged. Carry on!"
        ]
    )
}
